### ISSUE TITLE
Final rush for ViSP 3.3.0 release

### ISSUE THREAD

**Issue by fspindle** [lagadic/visp#698]
Deadline is February 15th.

Thinks that need to be done before:
- [x] Compat with OpenCV 4.2.0 (see issue #697)
- [x] Introduce PR #693 Add vpImageDraw and vpFont
- [x] Introduce PR #695 Update Java AprilTag sample
- [x] Introduce PR #696 Some various fixes
- [ ] Check if debian packaging is ok by considering lintian potential warnings
- [x] Update all the doxygen tutorials mainly those dealing with installation from source

Test build with last 3rd party releases:
- [x] OpenCV 4.2.0
- [x] cmake 3.16.4
- [x] libfranka 0.7.1
- [x] librealsense 2.32.1
- [x] eigen 3.3.7
- [x] GTK
- [x] MKL
- [x] Atlas
- [x] Netlib
- [x] OpenBLAS
- [x] GSL

Test ROS packages
- [x] [vision_visp](https://github.com/lagadic/vision_visp/)
- [x] [visp_ros](https://github.com/lagadic/visp_ros)
- [x] [demo_pioneer](https://github.com/lagadic/demo_pioneer)

Make advanced tests
- [x] iOS
- [x] Java
- [x] Android
- [x] raspberry Pi
- [x] Jetson TX2
- [ ] Odroid
- [ ] Unity
- [x] Debian sid
- [x] WinXP Ultrasonix machine with Visual Studio 2010
- [x] build with deprecated functions off
- [x] build with `pkg-config`and `visp.pc` (`robotpkg` and `teleky3` is a good candidate)

Build ViSP as static or dynamic libraries
- On Ubuntu platform

|  build external  project with |  static build |  static install |  dynamic build |  dynamic install |
|-------------------------------|---------------|-----------------|----------------|------------------|
| pkg-config                    | NA            | [ ]             | NA             | [ ]              |
| visp-config                   | [ ]           | [ ]             | [ ]            | [ ]              |
| cmake                         | [ ]           | [ ]             | [ ]            | [ ]              |

- On MacOS platform

|  build external  project with |  static build |  static install |  dynamic build |  dynamic install |
|-------------------------------|---------------|-----------------|----------------|------------------|
| pkg-config                    | NA            | [ ]             | NA             | [ ]              |
| visp-config                   | [ ]           | [ ]             | [ ]            | [ ]              |
| cmake                         | [ ]           | [ ]             | [ ]            | [ ]              |

- On Windows platform

|  build external  project with |  static build |  static install |  dynamic build |  dynamic install |
|-------------------------------|---------------|-----------------|----------------|------------------|
| visp-config                   | [ ]           | [ ]             | [ ]            | [ ]              |
| cmake                         | [ ]           | [ ]             | [ ]            | [ ]              |

Test other software that depends on ViSP with ViSP from installation
- [x] [UsTK](https://github.com/lagadic/ustk)
- [x] [ustk-sample](https://github.com/lagadic/ustk-sample)
- [x] [visp_sample](https://github.com/lagadic/visp_sample)
- [x] [visp_started](https://github.com/lagadic/visp_started)
- [x] [visp_contrib](https://github.com/lagadic/visp_contrib)
- [x] [camera_localization](https://github.com/lagadic/camera_localization)
- [x] All the robots dedicated apps on Ubuntu 16.04 (`gantry`)
- [x] All the robots dedicated apps on Ubuntu 18.04 (`wineck`)
- [x] All the robots dedicated apps on ArchLinux (`flylab-gs`)
